mv -v ./reset-nema-mode.sh ./troubleshoot
mv -v ./2.sh ./troubleshoot
mv -v ./reset-nema-mode-without-daemon.sh ./troubleshoot
mv -v ./gpscat.sh ./troubleshoot
mv -v ./1.sh ./troubleshoot
mv -v ./doit.sh ./troubleshoot
mv -v ./mv.sh ./troubleshoot
mv -v ./catttyS0.sh ./troubleshoot
mv -v ./launch-gpsd-daemon-debug-mode.sh ./troubleshoot
mv -v ./launch-gpsd-daemon.sh ./troubleshoot
